ch_cookie_consent:
    theme: 'dark' # light, dark
    categories: # Below are the default supported categories
        - 'analytics'
        - 'tracking'
        - 'marketing'
        - 'social_media'
    use_logger: false # Logs user actions to database
    position: 'bottom' # top, bottom
