<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRwJzMzN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRwJzMzN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRwJzMzN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRwJzMzN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRwJzMzN\App_KernelDevDebugContainer([
    'container.build_hash' => 'RwJzMzN',
    'container.build_id' => 'c73dc154',
    'container.build_time' => 1587598964,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRwJzMzN');
